<?php
$TWIG['categories'] = array(
	'som animasjon',
	'som arrangør',
	'med band',
	'med cheerleading',
	'med dans',
	'med elektronika',
	'med film',
	'med foto',
	'med design',
	'med håndarbeid',
	'med teater',
	'med journalistikk',
	'med kampsport',
	'som konferansier',
	'med kostymedesign',
	'med visuell kunst',
	'med litteratur',
	'med musikk',
	'i nettredaksjonen',
	'med nysirkus',
	'med sang',
	'som scenetekniker',
	'med stand-up',
	'med teater',
	'med tegning',
	'som tryllekunstner',
);