<?php
$TWIG['categories'] = array(
	'med musikk',
	'med dans',
	'med sang',
	'med film',
	'med teater',
	'med foto',
	'med design',
	'med band',
	'med litteratur',
	'med visuell kunst',

	'som arrangør',
	'med cheerleading',
	'med håndarbeid',
	'med teater',
	'som journalist',
	'med kampsport',
	'som konferansier',
	'i nettredaksjonen',
	'med nysirkus',
	'som scenetekniker',
	'med stand-up',
	'med tegning',
	'som tryllekunstner',
);

#	'med animasjon',
#	'med elektronika',
#	'med kostymedesign',
